/****************************************************************************
	This file was generated by Golific.

	Do not edit this file. If you do, your changes will be overwritten the next
	time 'generate' is invoked.
******************************************************************************/

package gopal

import (
	"encoding/json"
)

/*****************************

Payment struct

******************************/
func NewPayment() *Payment {
	return &Payment{
		private: private_1d0s5l86p45sy{},
	}
}

type Payment struct {
	private private_1d0s5l86p45sy
	*connection
	ExperienceProfileId string `json:"experience_profile_id"`
	*payment_error
}

type private_1d0s5l86p45sy struct {
	Intent        intentEnum        `json:"intent,omitempty"`
	Payer         payer             `json:"payer,omitempty"`
	Transactions  Transactions      `json:"transactions,omitempty"`
	RedirectUrls  Redirects         `json:"redirect_urls,omitempty"`
	State         stateEnum         `json:"state,omitempty"`
	Id            string            `json:"id,omitempty"`
	FailureReason FailureReasonEnum `json:"failure_reason,omitempty"`
	CreateTime    dateTime          `json:"create_time,omitempty"`
	UpdateTime    dateTime          `json:"update_time,omitempty"`
	Links         links             `json:"links,omitempty"`
}

type json_1d0s5l86p45sy struct {
	*private_1d0s5l86p45sy
	*connection
	ExperienceProfileId string `json:"experience_profile_id"`
	*payment_error
}

func (self *Payment) Intent() intentEnum {
	return self.private.Intent
}

func (self *Payment) Payer() payer {
	return self.private.Payer
}

func (self *Payment) Transactions() Transactions {
	return self.private.Transactions
}

func (self *Payment) RedirectUrls() Redirects {
	return self.private.RedirectUrls
}

func (self *Payment) State() stateEnum {
	return self.private.State
}

func (self *Payment) Id() string {
	return self.private.Id
}

func (self *Payment) FailureReason() FailureReasonEnum {
	return self.private.FailureReason
}

func (self *Payment) CreateTime() dateTime {
	return self.private.CreateTime
}

func (self *Payment) UpdateTime() dateTime {
	return self.private.UpdateTime
}

func (self *Payment) Links() links {
	return self.private.Links
}

func (self *Payment) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1d0s5l86p45sy{
		&self.private,
		self.connection,
		self.ExperienceProfileId,
		self.payment_error,
	})
}

func (self *Payment) UnmarshalJSON(j []byte) error {
	var temp json_1d0s5l86p45sy
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_1d0s5l86p45sy
	self.connection = temp.connection
	self.ExperienceProfileId = temp.ExperienceProfileId
	self.payment_error = temp.payment_error
	return nil
}

/*****************************

Transaction struct

******************************/
func NewTransaction() *Transaction {
	return &Transaction{
		private: private_kxdrvvky9zd6{},
	}
}

type Transaction struct {
	private        private_kxdrvvky9zd6
	Description    string         `json:"description,omitempty"`
	InvoiceNumber  string         `json:"invoice_number,omitempty"`
	Custom         string         `json:"custom,omitempty"`
	SoftDescriptor string         `json:"soft_descriptor,omitempty"`
	PaymentOptions paymentOptions `json:"payment_options,omitempty"`
}

type private_kxdrvvky9zd6 struct {
	ItemList         *itemList        `json:"item_list,omitempty"`
	Amount           amount           `json:"amount"`
	RelatedResources relatedResources `json:"related_resources,omitempty"`
}

type json_kxdrvvky9zd6 struct {
	*private_kxdrvvky9zd6
	Description    string         `json:"description,omitempty"`
	InvoiceNumber  string         `json:"invoice_number,omitempty"`
	Custom         string         `json:"custom,omitempty"`
	SoftDescriptor string         `json:"soft_descriptor,omitempty"`
	PaymentOptions paymentOptions `json:"payment_options,omitempty"`
}

func (self *Transaction) ItemList() *itemList {
	return self.private.ItemList
}

func (self *Transaction) Amount() amount {
	return self.private.Amount
}

func (self *Transaction) RelatedResources() relatedResources {
	return self.private.RelatedResources
}

func (self *Transaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_kxdrvvky9zd6{
		&self.private,
		self.Description,
		self.InvoiceNumber,
		self.Custom,
		self.SoftDescriptor,
		self.PaymentOptions,
	})
}

func (self *Transaction) UnmarshalJSON(j []byte) error {
	var temp json_kxdrvvky9zd6
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_kxdrvvky9zd6
	self.Description = temp.Description
	self.InvoiceNumber = temp.InvoiceNumber
	self.Custom = temp.Custom
	self.SoftDescriptor = temp.SoftDescriptor
	self.PaymentOptions = temp.PaymentOptions
	return nil
}

/*****************************

itemList struct

******************************/
func NewItemList() *itemList {
	return &itemList{
		private: private_1whizskbo8zm7{},
	}
}

type itemList struct {
	private private_1whizskbo8zm7
}

type private_1whizskbo8zm7 struct {
	Items           Items            `json:"items,omitempty"`
	ShippingAddress *ShippingAddress `json:"shipping_address,omitempty"`
}

type json_1whizskbo8zm7 struct {
	*private_1whizskbo8zm7
}

func (self *itemList) Items() Items {
	return self.private.Items
}

func (self *itemList) ShippingAddress() *ShippingAddress {
	return self.private.ShippingAddress
}

func (self *itemList) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1whizskbo8zm7{
		&self.private,
	})
}

func (self *itemList) UnmarshalJSON(j []byte) error {
	var temp json_1whizskbo8zm7
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_1whizskbo8zm7
	return nil
}

/*****************************

Item struct

******************************/
func NewItem() *Item {
	return &Item{
		private: private_1hhwhrpyt1acq{},
	}
}

type Item struct {
	private     private_1hhwhrpyt1acq
	Quantity    int64   `json:"quantity,string"`
	Name        string  `json:"name"`
	Price       float64 `json:"price,string"`
	Tax         float64 `json:"tax,omitempty"`
	Sku         string  `json:"sku,omitempty"`
	Description string  `json:"description,omitempty"`
}

type private_1hhwhrpyt1acq struct {
	Currency CurrencyTypeEnum `json:"currency"`
}

type json_1hhwhrpyt1acq struct {
	*private_1hhwhrpyt1acq
	Quantity    int64   `json:"quantity,string"`
	Name        string  `json:"name"`
	Price       float64 `json:"price,string"`
	Tax         float64 `json:"tax,omitempty"`
	Sku         string  `json:"sku,omitempty"`
	Description string  `json:"description,omitempty"`
}

func (self *Item) Currency() CurrencyTypeEnum {
	return self.private.Currency
}

func (self *Item) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1hhwhrpyt1acq{
		&self.private,
		self.Quantity,
		self.Name,
		self.Price,
		self.Tax,
		self.Sku,
		self.Description,
	})
}

func (self *Item) UnmarshalJSON(j []byte) error {
	var temp json_1hhwhrpyt1acq
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_1hhwhrpyt1acq
	self.Quantity = temp.Quantity
	self.Name = temp.Name
	self.Price = temp.Price
	self.Tax = temp.Tax
	self.Sku = temp.Sku
	self.Description = temp.Description
	return nil
}

/*****************************

_shared struct

******************************/

type _shared struct {
	private private_1dd8jbydz35uu
	*connection
	*identity_error
}

type private_1dd8jbydz35uu struct {
	Id            string    `json:"id,omitempty"`
	CreateTime    dateTime  `json:"create_time,omitempty"`
	UpdateTime    dateTime  `json:"update_time,omitempty"`
	State         stateEnum `json:"state,omitempty"`
	ParentPayment string    `json:"parent_payment,omitempty"`
	Links         links     `json:"links,omitempty"`
}

type json_1dd8jbydz35uu struct {
	*private_1dd8jbydz35uu
	*connection
	*identity_error
}

func (self *_shared) Id() string {
	return self.private.Id
}

func (self *_shared) CreateTime() dateTime {
	return self.private.CreateTime
}

func (self *_shared) UpdateTime() dateTime {
	return self.private.UpdateTime
}

func (self *_shared) State() stateEnum {
	return self.private.State
}

func (self *_shared) ParentPayment() string {
	return self.private.ParentPayment
}

func (self *_shared) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1dd8jbydz35uu{
		&self.private,
		self.connection,
		self.identity_error,
	})
}

func (self *_shared) UnmarshalJSON(j []byte) error {
	var temp json_1dd8jbydz35uu
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_1dd8jbydz35uu
	self.connection = temp.connection
	self.identity_error = temp.identity_error
	return nil
}

/*****************************

Authorization struct

******************************/

type Authorization struct {
	private private_nmejlqdyih0l
	_shared
}

type private_nmejlqdyih0l struct {
	Amount             amount                 `json:"amount"`
	BillingAgreementId string                 `json:"billing_agreement_id"`
	PaymentMode        paymentModeEnum        `json:"payment_mode"`
	ReasonCode         reasonCodeEnum         `json:"reason_code"`
	ValidUntil         dateTime               `json:"valid_until"`
	ClearingTime       string                 `json:"clearing_time"`
	ProtectionElig     protectionEligEnum     `json:"protection_eligibility"`
	ProtectionEligType protectionEligTypeEnum `json:"protection_eligibility_type"`
	FmfDetails         fmfDetails             `json:"fmf_details"`
}

type json_nmejlqdyih0l struct {
	*private_nmejlqdyih0l
	_shared
}

func (self *Authorization) Amount() amount {
	return self.private.Amount
}

func (self *Authorization) BillingAgreementId() string {
	return self.private.BillingAgreementId
}

func (self *Authorization) PaymentMode() paymentModeEnum {
	return self.private.PaymentMode
}

func (self *Authorization) ReasonCode() reasonCodeEnum {
	return self.private.ReasonCode
}

func (self *Authorization) ValidUntil() dateTime {
	return self.private.ValidUntil
}

func (self *Authorization) ClearingTime() string {
	return self.private.ClearingTime
}

func (self *Authorization) ProtectionElig() protectionEligEnum {
	return self.private.ProtectionElig
}

func (self *Authorization) ProtectionEligType() protectionEligTypeEnum {
	return self.private.ProtectionEligType
}

func (self *Authorization) FmfDetails() fmfDetails {
	return self.private.FmfDetails
}

func (self *Authorization) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_nmejlqdyih0l{
		&self.private,
		self._shared,
	})
}

func (self *Authorization) UnmarshalJSON(j []byte) error {
	var temp json_nmejlqdyih0l
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_nmejlqdyih0l
	self._shared = temp._shared
	return nil
}

/*****************************

Capture struct

******************************/
func NewCapture() *Capture {
	return &Capture{
		private: private_x5wpq5pilh16{},
	}
}

type Capture struct {
	private private_x5wpq5pilh16
	_shared
	TransactionFee currency `json:"transaction_fee"`
	IsFinalCapture bool     `json:"is_final_capture,omitempty"`
}

type private_x5wpq5pilh16 struct {
	Amount amount `json:"amount"`
}

type json_x5wpq5pilh16 struct {
	*private_x5wpq5pilh16
	_shared
	TransactionFee currency `json:"transaction_fee"`
	IsFinalCapture bool     `json:"is_final_capture,omitempty"`
}

func (self *Capture) Amount() amount {
	return self.private.Amount
}

func (self *Capture) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_x5wpq5pilh16{
		&self.private,
		self._shared,
		self.TransactionFee,
		self.IsFinalCapture,
	})
}

func (self *Capture) UnmarshalJSON(j []byte) error {
	var temp json_x5wpq5pilh16
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_x5wpq5pilh16
	self._shared = temp._shared
	self.TransactionFee = temp.TransactionFee
	self.IsFinalCapture = temp.IsFinalCapture
	return nil
}

/*****************************

Sale struct

******************************/
func NewSale() *Sale {
	return &Sale{
		private: private_164mm37ihm6hd{},
	}
}

type Sale struct {
	private private_164mm37ihm6hd
	_shared
	Description      string   `json:"description,omitempty"`
	TransactionFee   currency `json:"transaction_fee"`
	ReceivableAmount currency `json:"receivable_amount"`
}

type private_164mm37ihm6hd struct {
	Amount                    amount                 `json:"amount"`
	PendingReason             pendingReasonEnum      `json:"pending_reason"`
	PaymentMode               paymentModeEnum        `json:"payment_mode"`
	ExchangeRate              string                 `json:"exchange_rate"`
	FmfDetails                fmfDetails             `json:"fmf_details"`
	ReceiptId                 string                 `json:"receipt_id"`
	ReasonCode                reasonCodeEnum         `json:"reason_code"`
	ProtectionEligibility     protectionEligEnum     `json:"protection_eligibility"`
	ProtectionEligibilityType protectionEligTypeEnum `json:"protection_eligibility_type"`
	ClearingTime              string                 `json:"clearing_time"`
	BillingAgreementId        string                 `json:"billing_agreement_id"`
}

type json_164mm37ihm6hd struct {
	*private_164mm37ihm6hd
	_shared
	Description      string   `json:"description,omitempty"`
	TransactionFee   currency `json:"transaction_fee"`
	ReceivableAmount currency `json:"receivable_amount"`
}

func (self *Sale) Amount() amount {
	return self.private.Amount
}

func (self *Sale) PendingReason() pendingReasonEnum {
	return self.private.PendingReason
}

func (self *Sale) PaymentMode() paymentModeEnum {
	return self.private.PaymentMode
}

func (self *Sale) ExchangeRate() string {
	return self.private.ExchangeRate
}

func (self *Sale) FmfDetails() fmfDetails {
	return self.private.FmfDetails
}

func (self *Sale) ReceiptId() string {
	return self.private.ReceiptId
}

func (self *Sale) ReasonCode() reasonCodeEnum {
	return self.private.ReasonCode
}

func (self *Sale) ProtectionEligibility() protectionEligEnum {
	return self.private.ProtectionEligibility
}

func (self *Sale) ProtectionEligibilityType() protectionEligTypeEnum {
	return self.private.ProtectionEligibilityType
}

func (self *Sale) ClearingTime() string {
	return self.private.ClearingTime
}

func (self *Sale) BillingAgreementId() string {
	return self.private.BillingAgreementId
}

func (self *Sale) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_164mm37ihm6hd{
		&self.private,
		self._shared,
		self.Description,
		self.TransactionFee,
		self.ReceivableAmount,
	})
}

func (self *Sale) UnmarshalJSON(j []byte) error {
	var temp json_164mm37ihm6hd
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_164mm37ihm6hd
	self._shared = temp._shared
	self.Description = temp.Description
	self.TransactionFee = temp.TransactionFee
	self.ReceivableAmount = temp.ReceivableAmount
	return nil
}

/*****************************

Refund struct

******************************/
func NewRefund() *Refund {
	return &Refund{
		private: private_9ug8amnp0efr{},
	}
}

type Refund struct {
	private private_9ug8amnp0efr
	_shared
	Description string `json:"description,omitempty"`
	Reason      string `json:"reason,omitempty"`
}

type private_9ug8amnp0efr struct {
	Amount    amount `json:"amount"`
	SaleId    string `json:"sale_id,omitempty"`
	CaptureId string `json:"capture_id,omitempty"`
}

type json_9ug8amnp0efr struct {
	*private_9ug8amnp0efr
	_shared
	Description string `json:"description,omitempty"`
	Reason      string `json:"reason,omitempty"`
}

func (self *Refund) Amount() amount {
	return self.private.Amount
}

func (self *Refund) SaleId() string {
	return self.private.SaleId
}

func (self *Refund) CaptureId() string {
	return self.private.CaptureId
}

func (self *Refund) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_9ug8amnp0efr{
		&self.private,
		self._shared,
		self.Description,
		self.Reason,
	})
}

func (self *Refund) UnmarshalJSON(j []byte) error {
	var temp json_9ug8amnp0efr
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_9ug8amnp0efr
	self._shared = temp._shared
	self.Description = temp.Description
	self.Reason = temp.Reason
	return nil
}

/*****************************

amount struct

******************************/
func NewAmount() *amount {
	return &amount{
		private: private_sv7a3sk9gwkg{},
	}
}

type amount struct {
	private private_sv7a3sk9gwkg
	Details *details `json:"details,omitempty"`
}

type private_sv7a3sk9gwkg struct {
	Currency CurrencyTypeEnum `json:"currency"`
	Total    float64          `json:"total"`
}

type json_sv7a3sk9gwkg struct {
	*private_sv7a3sk9gwkg
	Details *details `json:"details,omitempty"`
}

func (self *amount) Currency() CurrencyTypeEnum {
	return self.private.Currency
}

func (self *amount) Total() float64 {
	return self.private.Total
}

func (self *amount) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_sv7a3sk9gwkg{
		&self.private,
		self.Details,
	})
}

func (self *amount) UnmarshalJSON(j []byte) error {
	var temp json_sv7a3sk9gwkg
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_sv7a3sk9gwkg
	self.Details = temp.Details
	return nil
}

/*****************************

link struct

******************************/
func NewLink() *link {
	return &link{
		private: private_1il4e0y99nthg{},
	}
}

type link struct {
	private private_1il4e0y99nthg
}

type private_1il4e0y99nthg struct {
	Href   string      `json:"href,omitempty"`
	Rel    relTypeEnum `json:"rel,omitempty"`
	Method string      `json:"method,omitempty"`
}

type json_1il4e0y99nthg struct {
	*private_1il4e0y99nthg
}

func (self *link) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1il4e0y99nthg{
		&self.private,
	})
}

func (self *link) UnmarshalJSON(j []byte) error {
	var temp json_1il4e0y99nthg
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_1il4e0y99nthg
	return nil
}

/*****************************

currency struct

******************************/
func NewCurrency() *currency {
	return &currency{
		private: private_1sodnbr0b4kng{},
	}
}

type currency struct {
	private  private_1sodnbr0b4kng
	Currency string `json:"currency"`
	Value    string `json:"value"`
}

type private_1sodnbr0b4kng struct{}

type json_1sodnbr0b4kng struct {
	*private_1sodnbr0b4kng
	Currency string `json:"currency"`
	Value    string `json:"value"`
}

func (self *currency) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1sodnbr0b4kng{
		&self.private,
		self.Currency,
		self.Value,
	})
}

func (self *currency) UnmarshalJSON(j []byte) error {
	var temp json_1sodnbr0b4kng
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_1sodnbr0b4kng
	self.Currency = temp.Currency
	self.Value = temp.Value
	return nil
}

/*****************************

fmfDetails struct

******************************/
func NewFmfDetails() *fmfDetails {
	return &fmfDetails{
		private: private_1d63lg9ea08rw{},
	}
}

type fmfDetails struct {
	private private_1d63lg9ea08rw
}

type private_1d63lg9ea08rw struct {
	FilterType  fmfFilterEnum `json:"filter_type"`
	FilterID    filterIdEnum  `json:"filter_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
}

type json_1d63lg9ea08rw struct {
	*private_1d63lg9ea08rw
}

func (self *fmfDetails) FilterType() fmfFilterEnum {
	return self.private.FilterType
}

func (self *fmfDetails) FilterID() filterIdEnum {
	return self.private.FilterID
}

func (self *fmfDetails) Name() string {
	return self.private.Name
}

func (self *fmfDetails) Description() string {
	return self.private.Description
}

func (self *fmfDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1d63lg9ea08rw{
		&self.private,
	})
}

func (self *fmfDetails) UnmarshalJSON(j []byte) error {
	var temp json_1d63lg9ea08rw
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_1d63lg9ea08rw
	return nil
}

/*****************************

payer struct

******************************/
func NewPayer() *payer {
	return &payer{
		private: private_1oaibylkd6w5p{},
	}
}

type payer struct {
	private            private_1oaibylkd6w5p
	PaymentMethod      PaymentMethodEnum  `json:"payment_method,omitempty"`
	FundingInstruments fundingInstruments `json:"funding_instruments,omitempty"`
	PayerInfo          *payerInfo         `json:"payer_info,omitempty"`
	Status             payerStatusEnum    `json:"status,omitempty"`
}

type private_1oaibylkd6w5p struct{}

type json_1oaibylkd6w5p struct {
	*private_1oaibylkd6w5p
	PaymentMethod      PaymentMethodEnum  `json:"payment_method,omitempty"`
	FundingInstruments fundingInstruments `json:"funding_instruments,omitempty"`
	PayerInfo          *payerInfo         `json:"payer_info,omitempty"`
	Status             payerStatusEnum    `json:"status,omitempty"`
}

func (self *payer) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1oaibylkd6w5p{
		&self.private,
		self.PaymentMethod,
		self.FundingInstruments,
		self.PayerInfo,
		self.Status,
	})
}

func (self *payer) UnmarshalJSON(j []byte) error {
	var temp json_1oaibylkd6w5p
	if err := json.Unmarshal(j, &temp); err != nil {
		return err
	}
	self.private = *temp.private_1oaibylkd6w5p
	self.PaymentMethod = temp.PaymentMethod
	self.FundingInstruments = temp.FundingInstruments
	self.PayerInfo = temp.PayerInfo
	self.Status = temp.Status
	return nil
}
