/****************************************************************************
	This file was generated by Golific.

	Do not edit this file. If you do, your changes will be overwritten the next
	time 'generate' is invoked.
******************************************************************************/

package gopal

import (
	"encoding/json"
)

/*****************************

_shared struct

******************************/

type _shared struct {
	private private_ttcx1fnvzdun
	*connection
	*identity_error
}

type private_ttcx1fnvzdun struct {
	Id            string    `json:"id,omitempty"`
	CreateTime    dateTime  `json:"create_time,omitempty"`
	UpdateTime    dateTime  `json:"update_time,omitempty"`
	State         stateEnum `json:"state,omitempty"`
	ParentPayment string    `json:"parent_payment,omitempty"`
	Links         links     `json:"links,omitempty"`
}

type json_ttcx1fnvzdun struct {
	*private_ttcx1fnvzdun
	*connection
	*identity_error
}

func (self *_shared) Id() string {
	return self.private.Id
}

func (self *_shared) CreateTime() dateTime {
	return self.private.CreateTime
}

func (self *_shared) UpdateTime() dateTime {
	return self.private.UpdateTime
}

func (self *_shared) State() stateEnum {
	return self.private.State
}

func (self *_shared) ParentPayment() string {
	return self.private.ParentPayment
}

func (self *_shared) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_ttcx1fnvzdun{
		&self.private,
		self.connection,
		self.identity_error,
	})
}

func (self *_shared) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "id":
			err = json.Unmarshal(rawMsg, &self.private.Id)
		case "create_time":
			err = json.Unmarshal(rawMsg, &self.private.CreateTime)
		case "update_time":
			err = json.Unmarshal(rawMsg, &self.private.UpdateTime)
		case "state":
			err = json.Unmarshal(rawMsg, &self.private.State)
		case "parent_payment":
			err = json.Unmarshal(rawMsg, &self.private.ParentPayment)
		case "links":
			err = json.Unmarshal(rawMsg, &self.private.Links)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

Authorization struct

******************************/

// State items are: pending, authorized, captured, partially_captured, expired,
// voided
type Authorization struct {
	private private_x81su7h6yq85
	_shared
}

type private_x81su7h6yq85 struct {
	Amount             amount                 `json:"amount"`
	BillingAgreementId string                 `json:"billing_agreement_id"`
	PaymentMode        paymentModeEnum        `json:"payment_mode"`
	ReasonCode         reasonCodeEnum         `json:"reason_code"`
	ValidUntil         dateTime               `json:"valid_until"`
	ClearingTime       string                 `json:"clearing_time"`
	ProtectionElig     protectionEligEnum     `json:"protection_eligibility"`
	ProtectionEligType protectionEligTypeEnum `json:"protection_eligibility_type"`
	FmfDetails         fmfDetails             `json:"fmf_details"`
}

type json_x81su7h6yq85 struct {
	*private_x81su7h6yq85
	_shared
}

func (self *Authorization) Amount() amount {
	return self.private.Amount
}

func (self *Authorization) BillingAgreementId() string {
	return self.private.BillingAgreementId
}

func (self *Authorization) PaymentMode() paymentModeEnum {
	return self.private.PaymentMode
}

func (self *Authorization) ReasonCode() reasonCodeEnum {
	return self.private.ReasonCode
}

func (self *Authorization) ValidUntil() dateTime {
	return self.private.ValidUntil
}

func (self *Authorization) ClearingTime() string {
	return self.private.ClearingTime
}

func (self *Authorization) ProtectionElig() protectionEligEnum {
	return self.private.ProtectionElig
}

func (self *Authorization) ProtectionEligType() protectionEligTypeEnum {
	return self.private.ProtectionEligType
}

func (self *Authorization) FmfDetails() fmfDetails {
	return self.private.FmfDetails
}

func (self *Authorization) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_x81su7h6yq85{
		&self.private,
		self._shared,
	})
}

func (self *Authorization) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "amount":
			err = json.Unmarshal(rawMsg, &self.private.Amount)
		case "billing_agreement_id":
			err = json.Unmarshal(rawMsg, &self.private.BillingAgreementId)
		case "payment_mode":
			err = json.Unmarshal(rawMsg, &self.private.PaymentMode)
		case "reason_code":
			err = json.Unmarshal(rawMsg, &self.private.ReasonCode)
		case "valid_until":
			err = json.Unmarshal(rawMsg, &self.private.ValidUntil)
		case "clearing_time":
			err = json.Unmarshal(rawMsg, &self.private.ClearingTime)
		case "protection_eligibility":
			err = json.Unmarshal(rawMsg, &self.private.ProtectionElig)
		case "protection_eligibility_type":
			err = json.Unmarshal(rawMsg, &self.private.ProtectionEligType)
		case "fmf_details":
			err = json.Unmarshal(rawMsg, &self.private.FmfDetails)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

Capture struct

******************************/
func NewCapture() *Capture {
	return &Capture{
		private: private_1kjkd9r1khiwf{},
	}
}

// State values are: pending, completed, refunded, partially_refunded
type Capture struct {
	private private_1kjkd9r1khiwf
	_shared
	TransactionFee currency `json:"transaction_fee"`
	IsFinalCapture bool     `json:"is_final_capture,omitempty"`
}

type private_1kjkd9r1khiwf struct {
	Amount amount `json:"amount"`
}

type json_1kjkd9r1khiwf struct {
	*private_1kjkd9r1khiwf
	_shared
	TransactionFee currency `json:"transaction_fee"`
	IsFinalCapture bool     `json:"is_final_capture,omitempty"`
}

func (self *Capture) Amount() amount {
	return self.private.Amount
}

func (self *Capture) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1kjkd9r1khiwf{
		&self.private,
		self._shared,
		self.TransactionFee,
		self.IsFinalCapture,
	})
}

func (self *Capture) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "amount":
			err = json.Unmarshal(rawMsg, &self.private.Amount)
		case "transaction_fee":
			err = json.Unmarshal(rawMsg, &self.TransactionFee)
		case "is_final_capture":
			err = json.Unmarshal(rawMsg, &self.IsFinalCapture)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

Sale struct

******************************/
func NewSale() *Sale {
	return &Sale{
		private: private_1l7gspugeygid{},
	}
}

// State values are: pending; completed; refunded; partially_refunded
// TODO: PendingReason appears in the old docs under the general Sale object description
// but not under the lower "sale object" definition. The new docs have it
// marked as [DEPRECATED] in one area, but not another.
type Sale struct {
	private private_1l7gspugeygid
	_shared
	Description      string   `json:"description,omitempty"`
	TransactionFee   currency `json:"transaction_fee"`
	ReceivableAmount currency `json:"receivable_amount"`
}

type private_1l7gspugeygid struct {
	Amount                    amount                 `json:"amount"`
	PendingReason             pendingReasonEnum      `json:"pending_reason"`
	PaymentMode               paymentModeEnum        `json:"payment_mode"`
	ExchangeRate              string                 `json:"exchange_rate"`
	FmfDetails                fmfDetails             `json:"fmf_details"`
	ReceiptId                 string                 `json:"receipt_id"`
	ReasonCode                reasonCodeEnum         `json:"reason_code"`
	ProtectionEligibility     protectionEligEnum     `json:"protection_eligibility"`
	ProtectionEligibilityType protectionEligTypeEnum `json:"protection_eligibility_type"`
	ClearingTime              string                 `json:"clearing_time"`
	BillingAgreementId        string                 `json:"billing_agreement_id"`
}

type json_1l7gspugeygid struct {
	*private_1l7gspugeygid
	_shared
	Description      string   `json:"description,omitempty"`
	TransactionFee   currency `json:"transaction_fee"`
	ReceivableAmount currency `json:"receivable_amount"`
}

func (self *Sale) Amount() amount {
	return self.private.Amount
}

func (self *Sale) PendingReason() pendingReasonEnum {
	return self.private.PendingReason
}

func (self *Sale) PaymentMode() paymentModeEnum {
	return self.private.PaymentMode
}

func (self *Sale) ExchangeRate() string {
	return self.private.ExchangeRate
}

func (self *Sale) FmfDetails() fmfDetails {
	return self.private.FmfDetails
}

func (self *Sale) ReceiptId() string {
	return self.private.ReceiptId
}

func (self *Sale) ReasonCode() reasonCodeEnum {
	return self.private.ReasonCode
}

func (self *Sale) ProtectionEligibility() protectionEligEnum {
	return self.private.ProtectionEligibility
}

func (self *Sale) ProtectionEligibilityType() protectionEligTypeEnum {
	return self.private.ProtectionEligibilityType
}

func (self *Sale) ClearingTime() string {
	return self.private.ClearingTime
}

func (self *Sale) BillingAgreementId() string {
	return self.private.BillingAgreementId
}

func (self *Sale) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1l7gspugeygid{
		&self.private,
		self._shared,
		self.Description,
		self.TransactionFee,
		self.ReceivableAmount,
	})
}

func (self *Sale) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "amount":
			err = json.Unmarshal(rawMsg, &self.private.Amount)
		case "description":
			err = json.Unmarshal(rawMsg, &self.Description)
		case "transaction_fee":
			err = json.Unmarshal(rawMsg, &self.TransactionFee)
		case "receivable_amount":
			err = json.Unmarshal(rawMsg, &self.ReceivableAmount)
		case "pending_reason":
			err = json.Unmarshal(rawMsg, &self.private.PendingReason)
		case "payment_mode":
			err = json.Unmarshal(rawMsg, &self.private.PaymentMode)
		case "exchange_rate":
			err = json.Unmarshal(rawMsg, &self.private.ExchangeRate)
		case "fmf_details":
			err = json.Unmarshal(rawMsg, &self.private.FmfDetails)
		case "receipt_id":
			err = json.Unmarshal(rawMsg, &self.private.ReceiptId)
		case "reason_code":
			err = json.Unmarshal(rawMsg, &self.private.ReasonCode)
		case "protection_eligibility":
			err = json.Unmarshal(rawMsg, &self.private.ProtectionEligibility)
		case "protection_eligibility_type":
			err = json.Unmarshal(rawMsg, &self.private.ProtectionEligibilityType)
		case "clearing_time":
			err = json.Unmarshal(rawMsg, &self.private.ClearingTime)
		case "billing_agreement_id":
			err = json.Unmarshal(rawMsg, &self.private.BillingAgreementId)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

Refund struct

******************************/
func NewRefund() *Refund {
	return &Refund{
		private: private_d3kfk1ovnovf{},
	}
}

// State items are: pending; completed; failed
type Refund struct {
	private private_d3kfk1ovnovf
	_shared
	Description string `json:"description,omitempty"`
	Reason      string `json:"reason,omitempty"`
}

type private_d3kfk1ovnovf struct {
	Amount    amount `json:"amount"`
	SaleId    string `json:"sale_id,omitempty"`
	CaptureId string `json:"capture_id,omitempty"`
}

type json_d3kfk1ovnovf struct {
	*private_d3kfk1ovnovf
	_shared
	Description string `json:"description,omitempty"`
	Reason      string `json:"reason,omitempty"`
}

func (self *Refund) Amount() amount {
	return self.private.Amount
}

func (self *Refund) SaleId() string {
	return self.private.SaleId
}

func (self *Refund) CaptureId() string {
	return self.private.CaptureId
}

func (self *Refund) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_d3kfk1ovnovf{
		&self.private,
		self._shared,
		self.Description,
		self.Reason,
	})
}

func (self *Refund) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "amount":
			err = json.Unmarshal(rawMsg, &self.private.Amount)
		case "description":
			err = json.Unmarshal(rawMsg, &self.Description)
		case "reason":
			err = json.Unmarshal(rawMsg, &self.Reason)
		case "sale_id":
			err = json.Unmarshal(rawMsg, &self.private.SaleId)
		case "capture_id":
			err = json.Unmarshal(rawMsg, &self.private.CaptureId)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

amount struct

******************************/
func NewAmount() *amount {
	return &amount{
		private: private_iz1g0yj3zgim{},
	}
}

// Amount Object
// A`Transaction` object also may have an `ItemList`, which has dollar amounts.
// These amounts are used to calculate the `Total` field of the `Amount` object
//
// All other uses of `Amount` do have `shipping`, `shipping_discount` and
// `subtotal` to calculate the `Total`.
type amount struct {
	private private_iz1g0yj3zgim
	Details *details `json:"details,omitempty"`
}

type private_iz1g0yj3zgim struct {
	Currency CurrencyTypeEnum `json:"currency"`
	Total    float64          `json:"total"`
}

type json_iz1g0yj3zgim struct {
	*private_iz1g0yj3zgim
	Details *details `json:"details,omitempty"`
}

func (self *amount) Currency() CurrencyTypeEnum {
	return self.private.Currency
}

func (self *amount) Total() float64 {
	return self.private.Total
}

func (self *amount) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_iz1g0yj3zgim{
		&self.private,
		self.Details,
	})
}

func (self *amount) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "currency":
			err = json.Unmarshal(rawMsg, &self.private.Currency)
		case "total":
			err = json.Unmarshal(rawMsg, &self.private.Total)
		case "details":
			err = json.Unmarshal(rawMsg, &self.Details)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

details struct

******************************/
func NewDetails() *details {
	return &details{
		private: private_1jqarv0dvvky0{},
	}
}

type details struct {
	private private_1jqarv0dvvky0
	// Amount charged for shipping. 10 chars max, with support for 2 decimal places
	Shipping float64 `json:"shipping,omitempty"`
	// Amount being charged for handling fee. When `payment_method` is `paypal`
	HandlingFee float64 `json:"handling_fee,omitempty"`
	// Amount being charged for insurance fee. When `payment_method` is `paypal`
	Insurance float64 `json:"insurance,omitempty"`
	// Amount being discounted for shipping fee. When `payment_method` is `paypal`
	ShippingDiscount float64 `json:"shipping_discount,omitempty"`
}

type private_1jqarv0dvvky0 struct {
	// Amount of the subtotal of the items. REQUIRED if line items are specified.
	// 10 chars max, with support for 2 decimal places
	Subtotal float64 `json:"subtotal,omitempty"`
	// Amount charged for tax. 10 chars max, with support for 2 decimal places
	Tax float64 `json:"tax,omitempty"`
}

type json_1jqarv0dvvky0 struct {
	*private_1jqarv0dvvky0
	Shipping         float64 `json:"shipping,omitempty"`
	HandlingFee      float64 `json:"handling_fee,omitempty"`
	Insurance        float64 `json:"insurance,omitempty"`
	ShippingDiscount float64 `json:"shipping_discount,omitempty"`
}

func (self *details) Subtotal() float64 {
	return self.private.Subtotal
}

func (self *details) Tax() float64 {
	return self.private.Tax
}

func (self *details) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1jqarv0dvvky0{
		&self.private,
		self.Shipping,
		self.HandlingFee,
		self.Insurance,
		self.ShippingDiscount,
	})
}

func (self *details) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "subtotal":
			err = json.Unmarshal(rawMsg, &self.private.Subtotal)
		case "tax":
			err = json.Unmarshal(rawMsg, &self.private.Tax)
		case "shipping":
			err = json.Unmarshal(rawMsg, &self.Shipping)
		case "handling_fee":
			err = json.Unmarshal(rawMsg, &self.HandlingFee)
		case "insurance":
			err = json.Unmarshal(rawMsg, &self.Insurance)
		case "shipping_discount":
			err = json.Unmarshal(rawMsg, &self.ShippingDiscount)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

link struct

******************************/
func NewLink() *link {
	return &link{
		private: private_12ijpzm9c7t22{},
	}
}

type link struct {
	private private_12ijpzm9c7t22
}

type private_12ijpzm9c7t22 struct {
	Href   string      `json:"href,omitempty"`
	Rel    relTypeEnum `json:"rel,omitempty"`
	Method string      `json:"method,omitempty"`
}

type json_12ijpzm9c7t22 struct {
	*private_12ijpzm9c7t22
}

func (self *link) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_12ijpzm9c7t22{
		&self.private,
	})
}

func (self *link) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "href":
			err = json.Unmarshal(rawMsg, &self.private.Href)
		case "rel":
			err = json.Unmarshal(rawMsg, &self.private.Rel)
		case "method":
			err = json.Unmarshal(rawMsg, &self.private.Method)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

currency struct

******************************/
func NewCurrency() *currency {
	return &currency{
		private: private_ju8oo66j8ek2{},
	}
}

// Base object for all financial value related fields (balance, payment due, etc.)
type currency struct {
	private  private_ju8oo66j8ek2
	Currency string `json:"currency"`
	Value    string `json:"value"`
}

type private_ju8oo66j8ek2 struct{}

type json_ju8oo66j8ek2 struct {
	*private_ju8oo66j8ek2
	Currency string `json:"currency"`
	Value    string `json:"value"`
}

func (self *currency) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_ju8oo66j8ek2{
		&self.private,
		self.Currency,
		self.Value,
	})
}

func (self *currency) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "currency":
			err = json.Unmarshal(rawMsg, &self.Currency)
		case "value":
			err = json.Unmarshal(rawMsg, &self.Value)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}

/*****************************

fmfDetails struct

******************************/
func NewFmfDetails() *fmfDetails {
	return &fmfDetails{
		private: private_1fizzzctiogpp{},
	}
}

// This object represents Fraud Management Filter (FMF) details for a payment.
type fmfDetails struct {
	private private_1fizzzctiogpp
}

type private_1fizzzctiogpp struct {
	FilterType  fmfFilterEnum `json:"filter_type"`
	FilterID    filterIdEnum  `json:"filter_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
}

type json_1fizzzctiogpp struct {
	*private_1fizzzctiogpp
}

func (self *fmfDetails) FilterType() fmfFilterEnum {
	return self.private.FilterType
}

func (self *fmfDetails) FilterID() filterIdEnum {
	return self.private.FilterID
}

func (self *fmfDetails) Name() string {
	return self.private.Name
}

func (self *fmfDetails) Description() string {
	return self.private.Description
}

func (self *fmfDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(json_1fizzzctiogpp{
		&self.private,
	})
}

func (self *fmfDetails) UnmarshalJSON(j []byte) error {
	if len(j) == 4 && string(j) == "null" {
		return nil
	}

	m := make(map[string]json.RawMessage)

	err := json.Unmarshal(j, &m)
	if err != nil {
		return err
	}

	// For every property found, perform a separate UnmarshalJSON operation. This
	// prevents overwrite of values in 'self' where properties are absent.
	for key, rawMsg := range m {
		switch key {
		case "filter_type":
			err = json.Unmarshal(rawMsg, &self.private.FilterType)
		case "filter_id":
			err = json.Unmarshal(rawMsg, &self.private.FilterID)
		case "name":
			err = json.Unmarshal(rawMsg, &self.private.Name)
		case "description":
			err = json.Unmarshal(rawMsg, &self.private.Description)
		default:
			// Ignoring unknown property
		}

		if err != nil {
			return err
		}
	}
	return nil
}
